name: docker image (14)

on:
  workflow_dispatch:
    
jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BBDEPLOYMENT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BBDEPLOYMENT_DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: 14/bookworm
          push: true
          tags: |
            bneibaruch/postgres:14-latest
            bneibaruch/postgres:14-gh_${{github.run_number}}